### ISSUE TITLE
does not fully work

### ISSUE THREAD

**Issue by electriquo** [hensm/hide_private_mode#1]
[here is an example][1] why it does not fully work

[1]: https://codepen.io/fadupla/pen/EWxKRW

**Comment by hensm** [comment]
<strike>Still doesn't work, the script takes too long to load and I can't find a reliable way to manipulate the load order. Practically though, doesn't seem to matter, since real sites have a bunch of other stuff to load before they check for private mode.</strike>

ac40957, 486007b — Scratch that, fixed

**Comment by electriquo** [comment]
@hensm:
thank you! it works on a fresh firefox profile, but on a customized (harden) firefox profile it does not.
can you share your thoughts about it.

**Comment by hensm** [comment]
Depends what settings/extensions you have installed. Possibly another extension that messes with the page context?

I’d try enabling things one by one until you find whatever is causing a conflict.

**Comment by electriquo** [comment]
@hensm: your addon is the only one i enabled in private window\browsing. guess i will have to take a closer look on my `user.js`.
